import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
const backend = 'http://127.0.0.1:8011'
test('real scenario → explanation → acceptance → override → audit → browser refresh', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('combobox', { name: 'Try an example' }).selectOption('repeat')
  await page.getByRole('button', { name: 'Run example', exact: true }).click()
  await expect(page.locator('.decision-header')).toContainText('Medium')
  await expect(page.locator('.explanation .explanation-block')).toHaveCount(6)
  await expect(page.locator('.explanation')).toContainText('LLM disabled')
  await expect(page.locator('.rule-evidence')).toContainText('NURSE_CALL_REPEAT_GTE_3')
  await page.getByLabel('Reviewer ID').fill('Integration reviewer')
  await page.getByRole('button', { name: 'Accept Decision' }).click()
  await expect(page.locator('.decision-header')).toContainText('accepted')
  await page.getByRole('button', { name: 'Override', exact: true }).click()
  await page.getByLabel('New Priority').selectOption('High')
  await page.getByLabel(/Clinical Reason/).fill('Synthetic workflow verification')
  await page.getByRole('button', { name: 'Confirm Override' }).click()
  await expect(page.locator('.decision-header')).toContainText('High')
  await expect(page.locator('.decision-header')).toContainText('Original system decision: Medium')
  await page.getByRole('button', { name: 'Accept Decision' }).click()
  await expect(page.locator('#human-review')).toContainText('decision version: 1')
  const selected = page.locator('.alert-select[aria-current="true"]')
  const id = (await selected.getAttribute('aria-label'))!.replace('View alert ', '')
  await page.getByRole('button', { name: 'Audit Log', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Audit Log' })
  await dialog.getByRole('button', { name: id, exact: true }).click()
  await expect(dialog.locator('.audit-detail')).toContainText('Synthetic workflow verification')
  await expect(dialog.locator('.audit-detail')).toContainText('Accepted version 1: High')
  await expect(dialog.locator('.audit-detail')).toContainText('request correlation id')
  await page.keyboard.press('Escape')
  await page.reload()
  await page.getByRole('button', { name: `View alert ${id}`, exact: true }).click()
  await expect(page.locator('.decision-header')).toContainText('accepted')
  await expect(page.locator('.decision-header')).toContainText('High')
  await page.getByText('Review history', { exact: true }).click()
  await expect(page.locator('#human-review')).toContainText('Synthetic workflow verification')
})

test('real API keeps Critical-to-High override drafts and audit history isolated', async ({ page, request }) => {
  const critical = JSON.parse(readFileSync(new URL('../../sample_data/alerts_low_spo2.json', import.meta.url), 'utf8'))
  const high = JSON.parse(readFileSync(new URL('../../sample_data/alerts_tachycardia.json', import.meta.url), 'utf8'))
  critical.alert_id = 'INTEGRATION-CRITICAL'; high.alert_id = 'INTEGRATION-HIGH'
  expect((await request.post(`${backend}/alerts`, { data: critical })).status()).toBe(201)
  expect((await request.post(`${backend}/alerts`, { data: high })).status()).toBe(201)
  await page.goto('/')
  await page.getByRole('button', { name: 'View alert INTEGRATION-CRITICAL' }).click()
  await expect(page.getByRole('button', { name: 'Override', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Override', exact: true }).click()
  await expect(page.getByLabel('New Priority')).toHaveValue('Critical')
  await page.getByLabel(/Clinical Reason/).fill('Draft belongs to critical alert')
  await page.getByRole('button', { name: 'View alert INTEGRATION-HIGH' }).click()
  await expect(page.getByRole('button', { name: 'Override', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Override', exact: true }).click()
  await expect(page.getByLabel('New Priority')).toHaveValue('High')
  await expect(page.getByLabel(/Clinical Reason/)).toHaveValue('')
  const audit = await (await request.get(`${backend}/alerts/INTEGRATION-CRITICAL/audit`)).json()
  expect(audit.overrides).toEqual([])
  expect((await request.post(`${backend}/alerts`, { data: critical })).status()).toBe(409)
})
