import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
const fixture = JSON.parse(readFileSync(new URL('./fallback.json', import.meta.url), 'utf8'))
for (const width of [1440, 390]) test(`local rules-only explanation and audit provenance at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 })
  await page.route('**/alerts', route => route.fulfill({ json: [fixture] }))
  await page.route('**/alerts/*/audit', route => route.fulfill({ json: { triage_result: fixture, review_state: { effective_priority: fixture.final_priority, effective_route: fixture.final_route, decision_version: 0, review_status: 'unreviewed' }, overrides: [], feedback: [], acceptances: [] } }))
  await page.route(url => url.pathname === '/audit', route => route.fulfill({ json: [{ id: 1, alert_id: fixture.alert_id, alert_type: fixture.alert.alert_type, patient_id: fixture.alert.patient_id, unit: fixture.alert.unit, baseline_priority: fixture.final_priority, final_priority: fixture.final_priority, final_route: fixture.final_route, rule_confidence: fixture.rule_output.rule_confidence, explanation_mode: 'rules_only', fallback_reason: 'provider_timeout', created_at: fixture.processed_at, override_count: 0, feedback_count: 0, acceptance_count: 0 }] }))
  await page.goto('/')
  const explanation = page.locator('.explanation')
  await expect(explanation).toContainText('No live provider call was made')
  await expect(explanation.locator('.fallback-label')).toContainText('Provider timeout')
  await expect(explanation).toContainText('NO_RULE_MATCHED:')
  await expect(explanation).toContainText('Insufficient data:')
  await expect(explanation.locator('.explanation-block')).toHaveCount(6)
  for (const section of await explanation.locator('.explanation-block').all()) await expect(section).not.toContainText('No verification guidance was returned')
  await expect(explanation.locator('.observations')).toContainText('Not provided')
  await expect(explanation.locator('.rule-evidence')).toContainText('default Low / Bedside Nurse decision applies')
  await expect(explanation).toContainText('Verify unavailable rule inputs')
  await expect(page.locator('.decision-header')).toContainText('Low')
  await expect(page.getByRole('button', { name: 'Accept Decision' })).toBeEnabled()
  await page.getByRole('button', { name: 'Audit Log', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Audit Log' })
  await expect(dialog).toContainText('Provider timeout')
  await expect(dialog).toContainText('Recorded rules explanation')
  await page.keyboard.press('Escape')
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  await page.screenshot({ path: `test-results/fallback-${width}.png`, fullPage: true })
})
