import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
const fixture = JSON.parse(readFileSync(new URL('./alert.json', import.meta.url), 'utf8'))
const items = ['B', 'A', 'Z'].map((id, index) => ({ ...fixture, alert_id: id, alert: { ...fixture.alert, alert_id: id, patient_id: `PAT-${id}`, unit: index === 2 ? 'South' : 'North', timestamp: index === 2 ? '2025-02-01T00:00:00Z' : '2025-01-01T00:00:00Z' }, review_state: { effective_priority: index === 2 ? 'High' : 'Critical', effective_route: 'Demo route', decision_version: 0, review_status: id === 'A' ? 'accepted' : 'unreviewed' } }))
test.beforeEach(async ({ page }) => {
  await page.route('**/alerts', route => route.fulfill({ json: items }))
  await page.route('**/alerts/*/audit', route => { const result = items.find(r => route.request().url().includes(`/alerts/${r.alert_id}/`))!; return route.fulfill({ json: { triage_result: result, review_state: result.review_state, overrides: [], feedback: [], acceptances: [] } }) })
  await page.route(url => url.pathname === '/audit', route => route.fulfill({ json: [] }))
  await page.goto('/')
})
test('compact queue sorting, combined filters, hidden selection and keyboard semantics', async ({ page }) => {
  await expect(page.locator('.alert-select')).toHaveText(['TachycardiaA', 'TachycardiaB', 'TachycardiaZ'])
  await page.getByLabel('Sort', { exact: true }).selectOption('newest')
  await expect(page.locator('.alert-select').first()).toHaveAttribute('aria-label', 'View alert Z')
  const button = page.getByRole('button', { name: 'View alert Z' })
  await button.focus(); await page.keyboard.press('Space')
  await expect(button).toHaveAttribute('aria-current', 'true')
  await expect(page.locator('.detail-pane')).toBeFocused()
  await page.getByLabel('Priority', { exact: true }).selectOption('Critical')
  await expect(page.getByRole('heading', { name: 'Explore an alert' })).toBeVisible()
  await expect(page.locator('.alert-detail')).toHaveCount(0)
  await page.getByLabel('Review status', { exact: true }).selectOption('accepted')
  await page.getByLabel('Search alert').fill(' north ')
  await expect(page.locator('.alert-select')).toHaveCount(1)
  await page.getByLabel('Search alert').fill('PAT-Z')
  await expect(page.getByText('No alerts match these filters.')).toBeVisible()
  await page.getByRole('button', { name: 'Clear queue filters' }).click()
  await expect(page.locator('.alert-select')).toHaveCount(3)
  await expect(page.locator('.alert-detail')).toHaveCount(0)
})
for (const width of [1440, 390]) test(`simulator and audit dialog focus, labels, Escape and restoration at ${width}`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 })
  for (const [openerName, title] of [['Advanced customization', 'Alert Simulator'], ['Audit Log', 'Audit Log']]) {
    const opener = page.getByRole('button', { name: openerName, exact: true })
    await opener.click()
    const dialog = page.getByRole('dialog', { name: title, exact: true })
    await expect(dialog).toBeVisible()
    await page.screenshot({ path: `test-results/dialog-${title.replaceAll(' ', '-')}-${width}.png` })
    expect(await dialog.evaluate(node => node.contains(document.activeElement))).toBe(true)
    if (title === 'Alert Simulator') { await expect(dialog.getByLabel('Patient ID *', { exact: true })).toBeVisible(); await expect(dialog.getByLabel('Alert time', { exact: true })).toBeAttached() }
    else await expect(dialog.getByLabel('Original priority')).toBeVisible()
    const controls = dialog.locator('button, input, select, textarea').filter({ visible: true })
    await controls.last().focus(); await page.keyboard.press('Tab')
    expect(await dialog.evaluate(node => node.contains(document.activeElement))).toBe(true)
    await page.keyboard.press('Shift+Tab')
    expect(await dialog.evaluate(node => node.contains(document.activeElement))).toBe(true)
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(opener).toBeFocused()
  }
})
